name: Feeds (RSS + News)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # roda de hora em hora (UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar deps (nenhuma necessária além do Node 20)
        run: npm init -y

      - name: Rodar gerador (usa o sitemap do WWW)
        env:
          SOURCE_SITEMAP: https://www.seumestrefinanceiro.com.br/sitemap.xml
          PUBLICATION_NAME: Seu Mestre Financeiro
          PUB_LANG: pt
        run: node build-feeds.mjs

      - name: Gerar sitemap.xml do site do git (opcional)
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://git.seumestrefinanceiro.com.br/

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add rss.xml sitemap-news.xml sitemap.xml || true
          git commit -m "auto: atualizar rss e news sitemap" || echo "sem alterações"
          git push
