name: Feeds (RSS + News)

on:
  workflow_dispatch:              # permite rodar manualmente
  schedule:
    - cron: "0 * * * *"           # 1x por hora (UTC)

permissions:
  contents: write                 # necessário para commitar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do repositório no $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # histórico completo (bom p/ generate-sitemap e lastmod)
      # Docs do checkout: coloca o repo em $GITHUB_WORKSPACE
      # https://github.com/actions/checkout
      # https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
      # :contentReference[oaicite:3]{index=3}

      # 2) Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      # :contentReference[oaicite:4]{index=4}

      # 3) Instalar deps necessárias sem alterar package.json
      - name: Instalar deps (fast-xml-parser + cheerio) sem salvar
        run: npm install --no-save fast-xml-parser cheerio

      # 4) Rodar gerador (usa o sitemap do WWW)
      - name: Rodar gerador (usa o sitemap do WWW)
        env:
          SOURCE_SITEMAP: https://www.seumestrefinanceiro.com.br/sitemap.xml
          PUBLICATION_NAME: Seu Mestre Financeiro
          PUB_LANG: pt
        run: node build-feeds.mjs

      # 5) Diagnóstico: ver se os XML estão sendo ignorados (opcional, mas útil)
      - name: Diagnóstico de ignore (opcional)
        run: |
          echo "==== .gitignore (se existir) ===="
          [ -f .gitignore ] && cat .gitignore || echo "(sem .gitignore)"
          echo "==== check-ignore ===="
          git check-ignore -v rss.xml sitemap-news.xml || true
      # Docs .gitignore e comportamento de ignore/forçar add
      # :contentReference[oaicite:5]{index=5}

      # 6) (Opcional) Gerar sitemap.xml do subdomínio git.*
      # - name: Gerar sitemap.xml do site do git (opcional)
      #   uses: cicirello/generate-sitemap@v1
      #   with:
      #    base-url-path: https://git.seumestrefinanceiro.com.br/
      # :contentReference[oaicite:6]{index=6}

      # 7) Commit e push — força add dos XML para driblar .gitignore
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          # força adicionar os XML mesmo que .gitignore ignore *.xml
          git add -f rss.xml sitemap-news.xml
          # adiciona o sitemap do git (se gerado)
          [ -f sitemap.xml ] && git add -f sitemap.xml || true
          # NÃO adiciona package.json/package-lock.json
          git commit -m "auto: atualizar rss.xml / sitemap-news.xml / sitemap.xml" || echo "sem alterações"
          git push
